### ISSUE TITLE
_prev_delay should be used in place of _last_delay

### ISSUE THREAD

**Issue by SineSwiper** [perlancar/perl-Algorithm-Backoff#1]
Within `_consider_actual_delay`, the `_last_delay` value is added into the calculations to offset whatever delay was used during the last attempt.  However, this value is set immediately after it's calculated and doesn't take into account jitter or min/max range limiters.  Thus, the real delay given back to the user and the `_last_delay` value are likely going to be different.

To account for that, you should just get rid of `_last_delay` and use `_prev_delay` instead.

**Comment by perlancar** [comment]
Thanks. PR welcome :)

**Comment by perlancar** [comment]
This breaks tests though. And I think the behavior specified in the test is the desired one.

    t/01-base.t ...... 1/? 
        #   Failed test at t/01-base.t line 69.
        #          got: '2'
        #     expected: '4'
    
        #   Failed test at t/01-base.t line 72.
        #          got: '0'
        #     expected: '1'
    
        #   Failed test at t/01-base.t line 78.
        #          got: '1'
        #     expected: '0'
        # Looks like you failed 3 tests of 5.
    
    #   Failed test 'attr: consider_actual_delay'
    #   at t/01-base.t line 79.

**Comment by SineSwiper** [comment]
Whoops, forgot to finish adjusting the unit tests.  The `max_delay` is set to 2, so it won't go past that, and I think it's causing the math to be a little off.  Let me re-work those `is` checks a bit.
